/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package k11finalsplf;

/**
 *
 * @author Josh
 */
public class movieSelectionUI extends javax.swing.JFrame {
    userCore obj = new userCore();
    /**
     * Creates new form movieSelectionUI
     */
    public movieSelectionUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        selectMovie1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        selectMovie2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        selectMovie3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        movieImage2 = new javax.swing.JLabel();
        movieImage3 = new javax.swing.JLabel();
        movieImage1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 1700));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(700, 1700));
        jScrollPane1.setViewportView(jPanel1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 1700));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("DUGA NI DULACA");
        jLabel1.setToolTipText("Ang DUGA sang maaslom");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(450, 210, 220, 40);

        selectMovie1.setText("Book");
        selectMovie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectMovie1ActionPerformed(evt);
            }
        });
        jPanel1.add(selectMovie1);
        selectMovie1.setBounds(440, 380, 180, 90);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("RICARTE MANTINIR ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(440, 680, 220, 40);

        selectMovie2.setText("Book");
        selectMovie2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectMovie2ActionPerformed(evt);
            }
        });
        jPanel1.add(selectMovie2);
        selectMovie2.setBounds(440, 880, 180, 90);

        jLabel4.setText("P" + obj.moviePrice2 + " | Comedy, Drama | 11AM-12PM, 4PM-5PM");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 850, 360, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("THE HUNCHBACK");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(440, 1200, 190, 32);

        selectMovie3.setText("Book");
        selectMovie3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectMovie3ActionPerformed(evt);
            }
        });
        jPanel1.add(selectMovie3);
        selectMovie3.setBounds(440, 1380, 180, 90);

        jLabel6.setText("P" + obj.moviePrice3 + " | Thriller, Drama | 6PM-7PM, 8PM-9PM");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(440, 1350, 340, 16);

        movieImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/k11finalsplf/DugaNiDulaca.jpg"))); // NOI18N
        jPanel1.add(movieImage2);
        movieImage2.setBounds(10, 30, 400, 509);

        movieImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/k11finalsplf/RicaMantinir.jpg"))); // NOI18N
        jPanel1.add(movieImage3);
        movieImage3.setBounds(10, 560, 400, 509);

        movieImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/k11finalsplf/LemuelHunchback.jpg"))); // NOI18N
        jPanel1.add(movieImage1);
        movieImage1.setBounds(10, 1090, 400, 509);

        jLabel2.setText("P" + obj.moviePrice1 + " | Tragedy, Drama | 8AM-10AM, 1PM-3PM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(440, 350, 330, 16);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selectMovie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectMovie1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movieTicketUI("movie1.txt", "Duga ni Dulaca").setVisible(true);
                
            }
            
        });
    }//GEN-LAST:event_selectMovie1ActionPerformed

    private void selectMovie2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectMovie2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movieTicketUI("movie2.txt", "Ricarte Mantinir").setVisible(true);
                
            }
        });
    }//GEN-LAST:event_selectMovie2ActionPerformed

    private void selectMovie3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectMovie3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movieTicketUI("movie3.txt", "The Hunchback").setVisible(true);
                
            }
        });
    }//GEN-LAST:event_selectMovie3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movieSelectionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movieSelectionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movieSelectionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movieSelectionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movieSelectionUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel movieImage1;
    private javax.swing.JLabel movieImage2;
    private javax.swing.JLabel movieImage3;
    private javax.swing.JButton selectMovie1;
    private javax.swing.JButton selectMovie2;
    private javax.swing.JButton selectMovie3;
    // End of variables declaration//GEN-END:variables
}
