/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package k11finalsplf;

import java.awt.Color;
import java.io.IOException;
import java.util.Arrays;
import java.util.Objects;
import javax.swing.JOptionPane;

import javax.swing.*;


/**
 *
 * @author Josh
 */
public class movieTicketUI extends javax.swing.JFrame {
    static String[] sectionA;
    boolean confirmBool;
    public String userName;
    JRadioButton[] buttons;
    userCore obj = new userCore();
    static String globalFileName;
    static String movieName;
    
    /**
     * Creates new form movieTicketUI
     */
    public movieTicketUI(String fileName, String movie) {
        globalFileName = fileName;
        movieName = movie;
        sectionA = obj.readSeatFile(fileName);
        System.out.println(Arrays.toString(sectionA));
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        A1 = new javax.swing.JRadioButton();
        A2 = new javax.swing.JRadioButton();
        A3 = new javax.swing.JRadioButton();
        A4 = new javax.swing.JRadioButton();
        A5 = new javax.swing.JRadioButton();
        A6 = new javax.swing.JRadioButton();
        A7 = new javax.swing.JRadioButton();
        A8 = new javax.swing.JRadioButton();
        A9 = new javax.swing.JRadioButton();
        A10 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        A11 = new javax.swing.JRadioButton();
        A12 = new javax.swing.JRadioButton();
        A13 = new javax.swing.JRadioButton();
        A14 = new javax.swing.JRadioButton();
        A15 = new javax.swing.JRadioButton();
        A16 = new javax.swing.JRadioButton();
        A17 = new javax.swing.JRadioButton();
        A18 = new javax.swing.JRadioButton();
        A19 = new javax.swing.JRadioButton();
        A20 = new javax.swing.JRadioButton();
        A21 = new javax.swing.JRadioButton();
        A22 = new javax.swing.JRadioButton();
        A23 = new javax.swing.JRadioButton();
        A24 = new javax.swing.JRadioButton();
        A25 = new javax.swing.JRadioButton();
        A26 = new javax.swing.JRadioButton();
        A27 = new javax.swing.JRadioButton();
        A28 = new javax.swing.JRadioButton();
        A29 = new javax.swing.JRadioButton();
        A30 = new javax.swing.JRadioButton();
        A31 = new javax.swing.JRadioButton();
        A32 = new javax.swing.JRadioButton();
        A33 = new javax.swing.JRadioButton();
        A34 = new javax.swing.JRadioButton();
        A35 = new javax.swing.JRadioButton();
        A36 = new javax.swing.JRadioButton();
        A37 = new javax.swing.JRadioButton();
        A38 = new javax.swing.JRadioButton();
        A39 = new javax.swing.JRadioButton();
        A40 = new javax.swing.JRadioButton();
        A41 = new javax.swing.JRadioButton();
        A42 = new javax.swing.JRadioButton();
        A43 = new javax.swing.JRadioButton();
        A44 = new javax.swing.JRadioButton();
        A45 = new javax.swing.JRadioButton();
        A46 = new javax.swing.JRadioButton();
        A47 = new javax.swing.JRadioButton();
        A48 = new javax.swing.JRadioButton();
        A49 = new javax.swing.JRadioButton();
        A50 = new javax.swing.JRadioButton();
        A51 = new javax.swing.JRadioButton();
        A52 = new javax.swing.JRadioButton();
        A53 = new javax.swing.JRadioButton();
        A54 = new javax.swing.JRadioButton();
        A55 = new javax.swing.JRadioButton();
        A56 = new javax.swing.JRadioButton();
        A57 = new javax.swing.JRadioButton();
        A58 = new javax.swing.JRadioButton();
        A59 = new javax.swing.JRadioButton();
        A60 = new javax.swing.JRadioButton();
        A61 = new javax.swing.JRadioButton();
        A62 = new javax.swing.JRadioButton();
        A63 = new javax.swing.JRadioButton();
        A64 = new javax.swing.JRadioButton();
        A65 = new javax.swing.JRadioButton();
        A66 = new javax.swing.JRadioButton();
        A67 = new javax.swing.JRadioButton();
        A68 = new javax.swing.JRadioButton();
        A69 = new javax.swing.JRadioButton();
        A70 = new javax.swing.JRadioButton();
        A71 = new javax.swing.JRadioButton();
        A72 = new javax.swing.JRadioButton();
        A73 = new javax.swing.JRadioButton();
        A74 = new javax.swing.JRadioButton();
        A75 = new javax.swing.JRadioButton();
        A76 = new javax.swing.JRadioButton();
        A77 = new javax.swing.JRadioButton();
        A78 = new javax.swing.JRadioButton();
        A79 = new javax.swing.JRadioButton();
        A80 = new javax.swing.JRadioButton();
        A81 = new javax.swing.JRadioButton();
        A82 = new javax.swing.JRadioButton();
        A83 = new javax.swing.JRadioButton();
        A84 = new javax.swing.JRadioButton();
        A85 = new javax.swing.JRadioButton();
        A86 = new javax.swing.JRadioButton();
        A87 = new javax.swing.JRadioButton();
        A88 = new javax.swing.JRadioButton();
        A89 = new javax.swing.JRadioButton();
        A90 = new javax.swing.JRadioButton();
        A91 = new javax.swing.JRadioButton();
        A92 = new javax.swing.JRadioButton();
        A93 = new javax.swing.JRadioButton();
        A94 = new javax.swing.JRadioButton();
        A95 = new javax.swing.JRadioButton();
        A96 = new javax.swing.JRadioButton();
        A97 = new javax.swing.JRadioButton();
        A98 = new javax.swing.JRadioButton();
        A99 = new javax.swing.JRadioButton();
        A100 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(A1);
        A1.setText("A1");

        buttonGroup1.add(A2);
        A2.setText("A2");

        buttonGroup1.add(A3);
        A3.setText("A3");

        buttonGroup1.add(A4);
        A4.setText("A4");

        buttonGroup1.add(A5);
        A5.setText("A5");

        buttonGroup1.add(A6);
        A6.setText("A6");

        buttonGroup1.add(A7);
        A7.setText("A7");

        buttonGroup1.add(A8);
        A8.setText("A8");

        buttonGroup1.add(A9);
        A9.setText("A9");

        buttonGroup1.add(A10);
        A10.setText("A10");

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatConfirm(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(0, 0, 0));
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("SCREEN HERE");

        buttonGroup1.add(A11);
        A11.setText("A11");

        buttonGroup1.add(A12);
        A12.setText("A12");

        buttonGroup1.add(A13);
        A13.setText("A13");

        buttonGroup1.add(A14);
        A14.setText("A14");

        buttonGroup1.add(A15);
        A15.setText("A15");

        buttonGroup1.add(A16);
        A16.setText("A16");

        buttonGroup1.add(A17);
        A17.setText("A17");

        buttonGroup1.add(A18);
        A18.setText("A18");

        buttonGroup1.add(A19);
        A19.setText("A19");

        buttonGroup1.add(A20);
        A20.setText("A20");

        buttonGroup1.add(A21);
        A21.setText("A21");

        buttonGroup1.add(A22);
        A22.setText("A22");

        buttonGroup1.add(A23);
        A23.setText("A23");

        buttonGroup1.add(A24);
        A24.setText("A24");

        buttonGroup1.add(A25);
        A25.setText("A25");

        buttonGroup1.add(A26);
        A26.setText("A26");

        buttonGroup1.add(A27);
        A27.setText("A27");

        buttonGroup1.add(A28);
        A28.setText("A28");

        buttonGroup1.add(A29);
        A29.setText("A29");

        buttonGroup1.add(A30);
        A30.setText("A30");

        buttonGroup1.add(A31);
        A31.setText("A31");

        buttonGroup1.add(A32);
        A32.setText("A32");

        buttonGroup1.add(A33);
        A33.setText("A33");

        buttonGroup1.add(A34);
        A34.setText("A34");

        buttonGroup1.add(A35);
        A35.setText("A35");

        buttonGroup1.add(A36);
        A36.setText("A36");

        buttonGroup1.add(A37);
        A37.setText("A37");

        buttonGroup1.add(A38);
        A38.setText("A38");

        buttonGroup1.add(A39);
        A39.setText("A39");

        buttonGroup1.add(A40);
        A40.setText("A40");

        buttonGroup1.add(A41);
        A41.setText("A41");

        buttonGroup1.add(A42);
        A42.setText("A42");

        buttonGroup1.add(A43);
        A43.setText("A43");

        buttonGroup1.add(A44);
        A44.setText("A44");

        buttonGroup1.add(A45);
        A45.setText("A45");

        buttonGroup1.add(A46);
        A46.setText("A46");

        buttonGroup1.add(A47);
        A47.setText("A47");

        buttonGroup1.add(A48);
        A48.setText("A48");

        buttonGroup1.add(A49);
        A49.setText("A49");

        buttonGroup1.add(A50);
        A50.setText("A50");

        buttonGroup1.add(A51);
        A51.setText("A51");

        buttonGroup1.add(A52);
        A52.setText("A52");

        buttonGroup1.add(A53);
        A53.setText("A53");

        buttonGroup1.add(A54);
        A54.setText("A54");

        buttonGroup1.add(A55);
        A55.setText("A55");

        buttonGroup1.add(A56);
        A56.setText("A56");

        buttonGroup1.add(A57);
        A57.setText("A57");

        buttonGroup1.add(A58);
        A58.setText("A58");

        buttonGroup1.add(A59);
        A59.setText("A59");

        buttonGroup1.add(A60);
        A60.setText("A60");

        buttonGroup1.add(A61);
        A61.setText("A61");

        buttonGroup1.add(A62);
        A62.setText("A62");

        buttonGroup1.add(A63);
        A63.setText("A63");

        buttonGroup1.add(A64);
        A64.setText("A64");

        buttonGroup1.add(A65);
        A65.setText("A65");

        buttonGroup1.add(A66);
        A66.setText("A66");

        buttonGroup1.add(A67);
        A67.setText("A67");

        buttonGroup1.add(A68);
        A68.setText("A68");

        buttonGroup1.add(A69);
        A69.setText("A69");

        buttonGroup1.add(A70);
        A70.setText("A70");

        buttonGroup1.add(A71);
        A71.setText("A71");

        buttonGroup1.add(A72);
        A72.setText("A72");

        buttonGroup1.add(A73);
        A73.setText("A73");

        buttonGroup1.add(A74);
        A74.setText("A74");

        buttonGroup1.add(A75);
        A75.setText("A75");

        buttonGroup1.add(A76);
        A76.setText("A76");

        buttonGroup1.add(A77);
        A77.setText("A77");

        buttonGroup1.add(A78);
        A78.setText("A78");

        buttonGroup1.add(A79);
        A79.setText("A79");

        buttonGroup1.add(A80);
        A80.setText("A80");

        buttonGroup1.add(A81);
        A81.setText("A81");

        buttonGroup1.add(A82);
        A82.setText("A82");

        buttonGroup1.add(A83);
        A83.setText("A83");

        buttonGroup1.add(A84);
        A84.setText("A84");

        buttonGroup1.add(A85);
        A85.setText("A85");

        buttonGroup1.add(A86);
        A86.setText("A86");

        buttonGroup1.add(A87);
        A87.setText("A87");

        buttonGroup1.add(A88);
        A88.setText("A88");

        buttonGroup1.add(A89);
        A89.setText("A89");

        buttonGroup1.add(A90);
        A90.setText("A90");

        buttonGroup1.add(A91);
        A91.setText("A91");

        buttonGroup1.add(A92);
        A92.setText("A92");

        buttonGroup1.add(A93);
        A93.setText("A93");

        buttonGroup1.add(A94);
        A94.setText("A94");

        buttonGroup1.add(A95);
        A95.setText("A95");

        buttonGroup1.add(A96);
        A96.setText("A96");

        buttonGroup1.add(A97);
        A97.setText("A97");

        buttonGroup1.add(A98);
        A98.setText("A98");

        buttonGroup1.add(A99);
        A99.setText("A99");

        buttonGroup1.add(A100);
        A100.setText("A100");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(350, 350, 350))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A35)
                        .addGap(105, 105, 105)
                        .addComponent(A36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A40))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(A21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(A22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(A23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(A24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(A25)
                            .addGap(105, 105, 105)
                            .addComponent(A26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(A27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(A28)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(A29)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(A30))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A15)
                                .addGap(105, 105, 105)
                                .addComponent(A16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A5)
                                .addGap(105, 105, 105)
                                .addComponent(A6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A10))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A45)
                        .addGap(105, 105, 105)
                        .addComponent(A46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A55)
                        .addGap(105, 105, 105)
                        .addComponent(A56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A59)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A60))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A61)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A62)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A63)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A64)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A65)
                        .addGap(105, 105, 105)
                        .addComponent(A66)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A67)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A68)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A69)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A70))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A71)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A72)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A73)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A74)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A75)
                        .addGap(105, 105, 105)
                        .addComponent(A76)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A77)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A78)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A79)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A80))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A81)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A82)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A83)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A84)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A85)
                        .addGap(105, 105, 105)
                        .addComponent(A86)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A87)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A88)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A89)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A90))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A91)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A92)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A93)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A94)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A95)
                        .addGap(105, 105, 105)
                        .addComponent(A96)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A97)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A98)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A99)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A100)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {A1, A10, A2, A3, A4, A5, A6, A7, A8, A9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {A11, A12, A13, A14, A15, A16, A17, A18, A19, A20});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A1)
                    .addComponent(A2)
                    .addComponent(A3)
                    .addComponent(A4)
                    .addComponent(A5)
                    .addComponent(A6)
                    .addComponent(A8)
                    .addComponent(A9)
                    .addComponent(A10)
                    .addComponent(A7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A11)
                    .addComponent(A12)
                    .addComponent(A13)
                    .addComponent(A14)
                    .addComponent(A15)
                    .addComponent(A16)
                    .addComponent(A18)
                    .addComponent(A19)
                    .addComponent(A20)
                    .addComponent(A17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A21)
                    .addComponent(A22)
                    .addComponent(A23)
                    .addComponent(A24)
                    .addComponent(A25)
                    .addComponent(A26)
                    .addComponent(A28)
                    .addComponent(A29)
                    .addComponent(A30)
                    .addComponent(A27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A31)
                    .addComponent(A32)
                    .addComponent(A33)
                    .addComponent(A34)
                    .addComponent(A35)
                    .addComponent(A36)
                    .addComponent(A38)
                    .addComponent(A39)
                    .addComponent(A40)
                    .addComponent(A37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A41)
                    .addComponent(A42)
                    .addComponent(A43)
                    .addComponent(A44)
                    .addComponent(A45)
                    .addComponent(A46)
                    .addComponent(A48)
                    .addComponent(A49)
                    .addComponent(A50)
                    .addComponent(A47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A51)
                    .addComponent(A52)
                    .addComponent(A53)
                    .addComponent(A54)
                    .addComponent(A55)
                    .addComponent(A56)
                    .addComponent(A58)
                    .addComponent(A59)
                    .addComponent(A60)
                    .addComponent(A57))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A61)
                    .addComponent(A62)
                    .addComponent(A63)
                    .addComponent(A64)
                    .addComponent(A65)
                    .addComponent(A66)
                    .addComponent(A68)
                    .addComponent(A69)
                    .addComponent(A70)
                    .addComponent(A67))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A71)
                    .addComponent(A72)
                    .addComponent(A73)
                    .addComponent(A74)
                    .addComponent(A75)
                    .addComponent(A76)
                    .addComponent(A78)
                    .addComponent(A79)
                    .addComponent(A80)
                    .addComponent(A77))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A81)
                    .addComponent(A82)
                    .addComponent(A83)
                    .addComponent(A84)
                    .addComponent(A85)
                    .addComponent(A86)
                    .addComponent(A88)
                    .addComponent(A89)
                    .addComponent(A90)
                    .addComponent(A87))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A91)
                    .addComponent(A92)
                    .addComponent(A93)
                    .addComponent(A94)
                    .addComponent(A95)
                    .addComponent(A96)
                    .addComponent(A98)
                    .addComponent(A99)
                    .addComponent(A100)
                    .addComponent(A97))
                .addGap(59, 59, 59)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {A1, A10, A2, A3, A4, A5, A6, A7, A8, A9});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {A11, A12, A13, A14, A15, A16, A17, A18, A19, A20});

        buttons = new JRadioButton[100];
        buttons[0] = A1;
        buttons[1] = A2;
        buttons[2] = A3;
        buttons[3] = A4;
        buttons[4] = A5;
        buttons[5] = A6;
        buttons[6] = A7;
        buttons[7] = A8;
        buttons[8] = A9;
        buttons[9] = A10;
        buttons[10] = A11;
        buttons[11] = A12;
        buttons[12] = A13;
        buttons[13] = A14;
        buttons[14] = A15;
        buttons[15] = A16;
        buttons[16] = A17;
        buttons[17] = A18;
        buttons[18] = A19;
        buttons[19] = A20;
        buttons[20] = A21;
        buttons[21] = A22;
        buttons[22] = A23;
        buttons[23] = A24;
        buttons[24] = A25;
        buttons[25] = A26;
        buttons[26] = A27;
        buttons[27] = A28;
        buttons[28] = A29;
        buttons[29] = A30;
        buttons[30] = A31;
        buttons[31] = A32;
        buttons[32] = A33;
        buttons[33] = A34;
        buttons[34] = A35;
        buttons[35] = A36;
        buttons[36] = A37;
        buttons[37] = A38;
        buttons[38] = A39;
        buttons[39] = A40;
        buttons[40] = A41;
        buttons[41] = A42;
        buttons[42] = A43;
        buttons[43] = A44;
        buttons[44] = A45;
        buttons[45] = A46;
        buttons[46] = A47;
        buttons[47] = A48;
        buttons[48] = A49;
        buttons[49] = A50;
        buttons[50] = A51;
        buttons[51] = A52;
        buttons[52] = A53;
        buttons[53] = A54;
        buttons[54] = A55;
        buttons[55] = A56;
        buttons[56] = A57;
        buttons[57] = A58;
        buttons[58] = A59;
        buttons[59] = A60;
        buttons[60] = A61;
        buttons[61] = A62;
        buttons[62] = A63;
        buttons[63] = A64;
        buttons[64] = A65;
        buttons[65] = A66;
        buttons[66] = A67;
        buttons[67] = A68;
        buttons[68] = A69;
        buttons[69] = A70;
        buttons[70] = A71;
        buttons[71] = A72;
        buttons[72] = A73;
        buttons[73] = A74;
        buttons[74] = A75;
        buttons[75] = A76;
        buttons[76] = A77;
        buttons[77] = A78;
        buttons[78] = A79;
        buttons[79] = A80;
        buttons[80] = A81;
        buttons[81] = A82;
        buttons[82] = A83;
        buttons[83] = A84;
        buttons[84] = A85;
        buttons[85] = A86;
        buttons[86] = A87;
        buttons[87] = A88;
        buttons[88] = A89;
        buttons[89] = A90;
        buttons[90] = A91;
        buttons[91] = A92;
        buttons[92] = A93;
        buttons[93] = A94;
        buttons[94] = A95;
        buttons[95] = A96;
        buttons[96] = A97;
        buttons[97] = A98;
        buttons[98] = A99;
        buttons[99] = A100;
        for (int i = 0; i < buttons.length; i++) {
            if (!(Objects.equals(sectionA[i], ("A" + (i + 1) )))) {
                buttons[i].setForeground(Color.RED);
            }
        }

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       
    private void seatConfirm(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatConfirm
        // TODO add your handling code here:
        for (int i = 0; i < buttons.length; i++) {
            if (buttons[i].isSelected()) {
                if (Objects.equals(sectionA[i], ("A" + (i + 1) ))) {
                    confirmBool = (0 == (JOptionPane.showConfirmDialog(this, "This seat is free. Would you like to take it?")));
                    if (confirmBool) {
                        while (true) {
                            userName = JOptionPane.showInputDialog(this, "Please state your name: ");
                            if (userName != null) {
                                break;
                            }
                        }
                        String seatNumber = "A" + (i + 1) + "-"+ userName;
                        obj.movieAddtoCart(i, seatNumber, movieName);
                        confirmBool = false;
                        
                        this.dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "This seat is already taken. Please select a different seat.");
                }
            }
        }
    }//GEN-LAST:event_seatConfirm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movieTicketUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movieTicketUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movieTicketUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movieTicketUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A1;
    private javax.swing.JRadioButton A10;
    private javax.swing.JRadioButton A100;
    private javax.swing.JRadioButton A11;
    private javax.swing.JRadioButton A12;
    private javax.swing.JRadioButton A13;
    private javax.swing.JRadioButton A14;
    private javax.swing.JRadioButton A15;
    private javax.swing.JRadioButton A16;
    private javax.swing.JRadioButton A17;
    private javax.swing.JRadioButton A18;
    private javax.swing.JRadioButton A19;
    private javax.swing.JRadioButton A2;
    private javax.swing.JRadioButton A20;
    private javax.swing.JRadioButton A21;
    private javax.swing.JRadioButton A22;
    private javax.swing.JRadioButton A23;
    private javax.swing.JRadioButton A24;
    private javax.swing.JRadioButton A25;
    private javax.swing.JRadioButton A26;
    private javax.swing.JRadioButton A27;
    private javax.swing.JRadioButton A28;
    private javax.swing.JRadioButton A29;
    private javax.swing.JRadioButton A3;
    private javax.swing.JRadioButton A30;
    private javax.swing.JRadioButton A31;
    private javax.swing.JRadioButton A32;
    private javax.swing.JRadioButton A33;
    private javax.swing.JRadioButton A34;
    private javax.swing.JRadioButton A35;
    private javax.swing.JRadioButton A36;
    private javax.swing.JRadioButton A37;
    private javax.swing.JRadioButton A38;
    private javax.swing.JRadioButton A39;
    private javax.swing.JRadioButton A4;
    private javax.swing.JRadioButton A40;
    private javax.swing.JRadioButton A41;
    private javax.swing.JRadioButton A42;
    private javax.swing.JRadioButton A43;
    private javax.swing.JRadioButton A44;
    private javax.swing.JRadioButton A45;
    private javax.swing.JRadioButton A46;
    private javax.swing.JRadioButton A47;
    private javax.swing.JRadioButton A48;
    private javax.swing.JRadioButton A49;
    private javax.swing.JRadioButton A5;
    private javax.swing.JRadioButton A50;
    private javax.swing.JRadioButton A51;
    private javax.swing.JRadioButton A52;
    private javax.swing.JRadioButton A53;
    private javax.swing.JRadioButton A54;
    private javax.swing.JRadioButton A55;
    private javax.swing.JRadioButton A56;
    private javax.swing.JRadioButton A57;
    private javax.swing.JRadioButton A58;
    private javax.swing.JRadioButton A59;
    private javax.swing.JRadioButton A6;
    private javax.swing.JRadioButton A60;
    private javax.swing.JRadioButton A61;
    private javax.swing.JRadioButton A62;
    private javax.swing.JRadioButton A63;
    private javax.swing.JRadioButton A64;
    private javax.swing.JRadioButton A65;
    private javax.swing.JRadioButton A66;
    private javax.swing.JRadioButton A67;
    private javax.swing.JRadioButton A68;
    private javax.swing.JRadioButton A69;
    private javax.swing.JRadioButton A7;
    private javax.swing.JRadioButton A70;
    private javax.swing.JRadioButton A71;
    private javax.swing.JRadioButton A72;
    private javax.swing.JRadioButton A73;
    private javax.swing.JRadioButton A74;
    private javax.swing.JRadioButton A75;
    private javax.swing.JRadioButton A76;
    private javax.swing.JRadioButton A77;
    private javax.swing.JRadioButton A78;
    private javax.swing.JRadioButton A79;
    private javax.swing.JRadioButton A8;
    private javax.swing.JRadioButton A80;
    private javax.swing.JRadioButton A81;
    private javax.swing.JRadioButton A82;
    private javax.swing.JRadioButton A83;
    private javax.swing.JRadioButton A84;
    private javax.swing.JRadioButton A85;
    private javax.swing.JRadioButton A86;
    private javax.swing.JRadioButton A87;
    private javax.swing.JRadioButton A88;
    private javax.swing.JRadioButton A89;
    private javax.swing.JRadioButton A9;
    private javax.swing.JRadioButton A90;
    private javax.swing.JRadioButton A91;
    private javax.swing.JRadioButton A92;
    private javax.swing.JRadioButton A93;
    private javax.swing.JRadioButton A94;
    private javax.swing.JRadioButton A95;
    private javax.swing.JRadioButton A96;
    private javax.swing.JRadioButton A97;
    private javax.swing.JRadioButton A98;
    private javax.swing.JRadioButton A99;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
